### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by dobrynski** [tremby/py-lightpack#1]
Any chance of updating for Python 3 support? Also adding the set mode command?

I'd love to be able to use this library for a lightpack light platform in Home Assistant.

**Comment by tremby** [comment]
Good idea. I just released v2.1.0 which works with Python 3. Let me know if you have any issues.

**Comment by mihalski** [comment]
Sorry, I only just had a chance to try it out.

With the example provided I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    lp = lightpack.Lightpack(led_map=led_map)
AttributeError: module 'lightpack' has no attribute 'Lightpack'
```

**Comment by tremby** [comment]
At 2017-08-12 16:50:30 -0700, mihalski wrote:
> Sorry, I only just had a chance to try it out.
> 
> With the example provided I get the following error:
> ```
> Traceback (most recent call last):
>   File "test.py", line 25, in <module>
>     lp = lightpack.Lightpack(led_map=led_map)
> AttributeError: module 'lightpack' has no attribute 'Lightpack'
> ```

I can't find this message on Github so I guess you found the issue?
