### ISSUE TITLE
No module named lightpack while i have already setup it (MAC OS)

### ISSUE THREAD

**Issue by tihoangyeudau** [tremby/py-lightpack#13]
i have already setup py-lightpack but my program still has this error:

```
cd '/Users/tihoangyeudau/.Prismatik/Plugins/WLED_WiFi/' && '/usr/bin/pythonw'  '/Users/tihoangyeudau/.Prismatik/Plugins/WLED_WiFi/WLED_WiFi.py'  && echo Exit status: $? && exit 1
Hoang-Mac:~ tihoangyeudau$ cd '/Users/tihoangyeudau/.Prismatik/Plugins/WLED_WiFi/' && '/usr/bin/pythonw'  '/Users/tihoangyeudau/.Prismatik/Plugins/WLED_WiFi/WLED_WiFi.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/tihoangyeudau/.Prismatik/Plugins/WLED_WiFi/WLED_WiFi.py", line 1, in <module>
    import lightpack, socket, configparser, os
ImportError: No module named lightpack
Hoang-Mac:WLED_WiFi tihoangyeudau$
```
My version of python: 3.7.5

**Comment by tremby** [comment]
I don't think I can really help you with this. This indicates either that you haven't installed the library properly, or that there's something wrong with your Python installation or configuration, or some issue with multiple versions of Python.

You didn't give any details of how you attempted to install the library. The readme suggests two options: via pip or from source. If you're using pip, does the pip you installed with install for the same python version that you're running (/usr/bin/pythonw)? If from source, did you run the setup script with the same python version?

Also, I don't have a Mac so I don't know what kind of complications that might be adding.

**Comment by tihoangyeudau** [comment]
> I don't think I can really help you with this. This indicates either that you haven't installed the library properly, or that there's something wrong with your Python installation or configuration, or some issue with multiple versions of Python.
> 
> You didn't give any details of how you attempted to install the library. The readme suggests two options: via pip or from source. If you're using pip, does the pip you installed with install for the same python version that you're running (/usr/bin/pythonw)? If from source, did you run the setup script with the same python version?
> 
> Also, I don't have a Mac so I don't know what kind of complications that might be adding.

thank you. i will try to reinstall mac os then setup it again
