### ISSUE TITLE
Scene luminosity setting changes disabled LEDs

### ISSUE THREAD

**Issue by David-Kopczynski** [tremby/py-lightpack#15]
Disabled LEDs get modified when using Scene luminosity, resulting in slightly blue LEDs where no color should be shown. This does not seem to be the case with all other settings as averaging or temperature/gamma. 

Ideally every LED is checked before applying any effects.

**Comment by tremby** [comment]
I don't know what any of this means. What do you mean by disabled LEDs? What is scene luminosity? What effects?

Are you sure your issue is related to this library?

**Comment by David-Kopczynski** [comment]
Whoops, must have accidentally created this issue on the wrong repo.
