### ISSUE TITLE
Suggest to loosen the dependency on boltons

### ISSUE THREAD

**Issue by Agnes-U** [tremby/py-lightpack#16]
Hi, your project py-lightpack(commit id: a47e52cd5dbe1898610ad8137081ab358d9b341b) requires "boltons==18.0.0" in its dependency. After analyzing the source code, we found that the following versions of boltons can also be suitable, i.e., boltons 16.2.2, 16.3.0, 16.3.1, 16.4.0, 16.4.1, 16.5.0, 16.5.1, 17.0.0, 17.1.0, 17.2.0, since all functions that you directly (1 APIs: boltons.socketutils.BufferedSocket.__init__) or indirectly (propagate to 1 boltons's internal APIs and 1 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on boltons from "boltons==18.0.0" to "boltons>=16.2.2,<=18.0.0". This will improve the applicability of py-lightpack and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on boltons?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by tremby** [comment]
Are you a robot?

**Comment by Agnes-U** [comment]
Thanks for your reply and question. No, I am not a bot. The above results are obtained automatically. I created the issue manually, and I can also pull a request(that would be great)!

**Comment by tremby** [comment]
It sounds like you are not a user of this package.

I would accept a pull request which eliminates this dependency and uses bulitins instead, and crucially which actually has been tested. But as is, I'm not interested; thank you.
